### ISSUE TITLE
How does one customize sector label style in pie chart series?

### ISSUE THREAD

**Issue by AlekseiYerokhinCrexi** [ag-grid/ag-charts#1138]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Please tell us about your environment:**

Linux Mint

-   **AG Charts version:** 9.1.1

-   **Language:** TypeScript 5.3.3

**Question** 
Does anyone know how to customize sector label style in pie chart series? E.g. i want them to be white on black series and black on white series. Wasn't able to find a way to do it, just a value displayed is customizable. Otherwise a color for ALL labels can be set.

**Comment by AG-DavidG** [comment]
Hello @AlekseiYerokhinCrexi ,

Thank you for the context.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
AG-8917 [Charts] Allow styling series labels on a per item basis

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Charts. Please use the functionality currently provided by AG Charts until this is delivered at a later point.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).

Thanks again for bringing this up with us.

Regards,

David
