### ISSUE TITLE
[Question] Reading, writing, and listening to internal state.

### ISSUE THREAD

**Issue by DevinLeamy** [ag-grid/ag-charts#1142]
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

I have the following grid. 
<img src="https://github.com/ag-grid/ag-charts/assets/45083086/cf8cfb1a-2782-4f21-b9bf-def9d326efe9" width="400" />

When I click one of the items in the legend it updates the view.
<img src="https://github.com/ag-grid/ag-charts/assets/45083086/e26ee765-731d-4d00-ab1c-f8ddf3b19c1f" width="400" />

I want this view update to take place on all of the clients that are viewing this grid. I'm wondering whether AgCharts provides a means to access (and set) this "internal" state, similar to how AgGrid provides `api.getColumnState` (https://www.ag-grid.com/javascript-data-grid/column-state/#save-and-apply). 

Thanks!

**Comment by AG-DavidG** [comment]
Hello @DevinLeamy ,

Thank you for the question.

To achieve this you would need to listen to legend click events and then update the `series.visible` option in the other charts based on that.

Please refer to our documentation about 
- [Legend click and double-click events](https://charts.ag-grid.com/javascript/events/#legend-events---legenditemclick-and-legenditemdoubleclick)
- [Updating an existing chart](https://charts.ag-grid.com/javascript/api-create-update/)
- [series.visible](https://charts.ag-grid.com/options/series/bar/#reference-AgBarSeriesOptions-visible)

However, we agree that making this easier would be a valuable addition to the product and we have added feature requests for this.

We have added these requirements to our backlog and we are tracking them with the following references and descriptions:
AG-8253 [Charts] Allow users to get the chart's current dynamic state
AG-10741 [Charts] Allow multiple chart instances to synchronise legend toggle

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Charts. Please use the functionality currently provided by AG Charts until this is delivered at a later point.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).

Thanks again for bringing this up with us.

Regards,

David
