### ISSUE TITLE
Documentation for AgTooltipRendererResult HTML capabilities

### ISSUE THREAD

**Issue by BradWells** [ag-grid/ag-charts#1156]
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Current behavior**

Ag Grid Documentation website does not say that AgTooltipRendererResult content field can contain HTML and it will render it as such.

**Expected behavior**

Description of AgTooltipRendererResult content field mentions it can contain HTML such as `<br />`

**Comment by AG-DavidG** [comment]
Hi @BradWells 

We have a section about tooltips on our documentation website, and it does mention this point.

See near the end of the https://charts.ag-grid.com/javascript/tooltips/#modifying-content-and-title section where we say that 
> The title and content fields returned can contain plain text or HTML.

Thanks

David
