### ISSUE TITLE
Undocumented minimum height?

### ISSUE THREAD

**Issue by nbran** [ag-grid/ag-charts#1169]
**I'm submitting a ...** (check one with "x")

```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/6Pz3d0kgbrV2l7hu?open=index.jsx

https://stackblitz.com/edit/new-wagmi-4ulaqb?file=src%2FApp.tsx,package.json

**Current behavior**

Charts inside containers with a height smaller than 300px overflow the container.

**Expected behavior**

The chart should automatically size up to the available height, as it happens for charts inside containers with a height >= 300px.

**Please tell us about your environment:**

Ubuntu 22, VSCode, NPM, React, Vite

-   **AG Charts version:** 9.1.1

-   **Browser:**
    - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0
    - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

-   **Language:** TypeScript 5.2.2

**Comment by AG-DavidG** [comment]
Hello @nbran ,
 
Thank you for the question.
 
We do have a default chart size which is used when a chart container does not inherit a specific from the parent element. This is what is happening in your scenario when using a flexbox.
You can read more about this at https://defensivecss.dev/tip/flexbox-min-content-size/.
 
To fix your example I suggest that you set `min-height: 0` in the div containing the chart container, as shown in https://plnkr.co/edit/dqUSvQLtXmpsIUTN?open=index.jsx, or remove that div altogether.
 
We agree that this behaviour could be improved and we have added a feature request for this.
 
We have added this requirement to our backlog and we are tracking it with the following reference and description:
AG-10200 Improve chart autosize mechanism
 
We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Charts. Please use the functionality currently provided by AG Charts until this is delivered at a later point.
 
You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/
 
The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).
 
Thanks again for bringing this up with us.
 
Regards,
 
David‍
