### ISSUE TITLE
jest testing ag grid charts angular17 9.1

### ISSUE THREAD

**Issue by PiotrMistu** [ag-grid/ag-charts#1202]
TypeError: Cannot read properties of null (reading 'canvas')

      18 |              component = fixture.componentInstance;
    > 20 |              fixture.detectChanges();

How to fix this dCh in jest on create test?

**Comment by AG-DavidG** [comment]
Hi @PiotrMistu 

Thank you for your query.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker or codesandbox sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,

David

**Comment by AG-DavidG** [comment]
Hi @PiotrMistu 

I am closing this issue as we do not have a reproducible scenario to demonstrate the problem you have described.

If you have a reproducible scenario then please let us know and we will be happy to investigate further.

Thanks

David
