### ISSUE TITLE
wrapHeaderText and autoHeaderHeight not working in aggrid-vue

### ISSUE THREAD

**Issue by tuantuanzi-code** [ag-grid/ag-charts#1316]
Hi,
    wrapHeaderText and autoHeaderHeight not working in my aggrid-vue. 
    part of my code:
    this.columnDefs = [
      {
        field: 'customer',
        headerName: 'Customer this is toooooo long',
        filter: 'agSetColumnFilter',
      },
      {
        field: 'change',
        headerName: 'Change Demo shows',
        enableRowGroup: true,
        enablePivot: true,
        filter: 'agSetColumnFilter',
        cellRenderer(params) {
          if (!params.data.change || params.data.change === 'NULL' || params.data.change === 'null') {
            return '-';
          }
          return `${params.data.change}`;
        },
      },
    ];
    this.defaultColDef = {
      resizable: true,
      sortable: true,
      filter: true,
      initialWidth: 100,
      wrapHeaderText: true,
      autoHeaderHeight: true,
    };
    however, my column header not wrapped. will cellRenderer exclusive with wrapText? not sure, but wrapText and autoHeight can work with flex:1 while wrapHeaderText and autoHeaderHeight still not working.
    could you please help?
     my AG-grid version is "ag-grid-vue": "^25.1.0"
Thanks!

**Comment by AG-Zoheil** [comment]
Hi @tuantuanzi-code,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

**Can you please raise the issue alongside an example in our issue section for the grid repository** as this is grid and not charts related: https://github.com/ag-grid/ag-grid/issues

We're looking forward to your response.

Kind regards,
Zoheil
