### ISSUE TITLE
AG Grid: Looking for component [] but it wasn't found.

### ISSUE THREAD

**Issue by theonlineaid** [ag-grid/ag-charts#1340]
**How can i solve this warning.**

```
ag-grid-react.js?v=27871630:19222 AG Grid: Looking for component [] but it wasn't found.
```
![Screenshot from 2024-03-28 15-59-11](https://github.com/ag-grid/ag-charts/assets/46064292/512febce-751e-4e99-b9b7-8f1206a941ed)

-   **AG Charts version:** ```  
"ag-grid-community": "^28.1.1",
    "ag-grid-enterprise": "^28.1.3",
    "ag-grid-react": "^28.1.1",
```
-   **Browser: Chrome**


-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-Zoheil** [comment]
Hi @theonlineaid,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Can you please raise the issue alongside an example in our **issue section for the grid repository as this is grid and not charts related**: https://github.com/ag-grid/ag-grid/issues

We're looking forward to your response.

Kind regards,
Zoheil
