### ISSUE TITLE
to use a Column Group Definition as autoGroupColumnDef

### ISSUE THREAD

**Issue by meghna786** [ag-grid/ag-charts#1391]
**I'm submitting a support request/ feature request

**Current behavior**

I want to use children headers in AutoGroupColumnDef,

I am rendering table with:
treeData: true,

and not providing column definition for this column in ColDefs array.
instead using

autoGroupColumnDef: {
headerName: 'Financials Statement',
floatingFilter: false,
cellRendererParams: {
suppressCount: true,
},
width:307,
pinned: 'left',
},

I just want this header to have nesting for eg-

marryChildren:true,
children:[
{ headerName: 'Financial Tags',
children:[
headerName:'Frequency',
children:[
headerName:' ',
]
]

}

Let me know if its possible or if there is any work around for this?

**Expected behavior**

I have attached a screen shot of the header nesting I want----

**Comment by meghna786** [comment]
![adaptable-issue](https://github.com/ag-grid/ag-charts/assets/66870732/c485eca0-f41e-4e64-a5e1-700b9b89e0c9)

**Comment by AG-Zoheil** [comment]
Hi @meghna786,

Thank you for submitting this on GitHub.

The functionality you are enquiring about (tree data) is an enterprise feature.

If you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/hc/en-us) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered.

Please also note that you have a raised a grid related question in our charts repo. Any discussions surrounding the grid can be found here: https://github.com/ag-grid/ag-grid/issues.

Looking forward to hearing from you via ZenDesk.

Kind regards,
Zoheil

**Comment by meghna786** [comment]
Can you please let me know here if its possible to acheive this or not? we are using tree Data in our project and we have commercial Application license from Adaptable Tools @AG-Zoheil

**Comment by AG-Zoheil** [comment]
Hi @meghna786,

Thanks for getting back. Adaptable Tools and AG Grid run on two separate licences. For AG Grid Enterprise features I can only reiterate to please contact us via the appropriate channels for support.

Please email info@ag-grid.com with your current AG Grid Enterprise key and request a support account for Zendesk if you don't already have one. Going forward this will be much smoother for you & your team.

Kind regards,
Zoheil
