### ISSUE TITLE
Trying to setQuickFilter function into the Detail grid using this.gridApi.forEachDetailGridInfo()

### ISSUE THREAD

**Issue by subash-DU** [ag-grid/ag-charts#1447]
this.gridApi.forEachDetailGridInfo((detailGridInfo:DetailGridInfo|any) => {
      detailGridInfo.api.setQuickFilter(this.filterValue);
});

**Comment by AG-Zoheil** [comment]
Hi @subash-DU,

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

**Can you please raise the issue alongside an example in our issue section for the grid repository as this is grid and not charts related:** https://github.com/ag-grid/ag-grid/issues

We're looking forward to your response.

Kind regards,
Zoheil
