### ISSUE TITLE
Broken type declaration ( wrong casing ) for Cartesian chart option ( solution included ) 

### ISSUE THREAD

**Issue by boldrack** [ag-grid/ag-charts#1605]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   A description of the detailed steps to reproduce your behaviour in one of our examples in our docs.
-   A Plunker.

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Cannot use AgCartesianChartOptions type from `ag-charts-community` to type a `AgChartOptions` which is a type of the options props passed to `AgChartsReact` 
This leads to an error like below 

```
src/components/dashboard/CustomerGainChart.tsx:25:22 - error TS2322: Type '{ title: { text: string; }; data: { month: string; subscriptions: number; services: number; products: number; }[]; series: { type: string; xKey: string; yKey: string; }[]; theme: { baseTheme: AgChartThemeName; }; legend: { ...; }; background: { ...; }; }' is not assignable to type 'AgChartOptions'.
  Type '{ title: { text: string; }; data: { month: string; subscriptions: number; services: number; products: number; }[]; series: { type: string; xKey: string; yKey: string; }[]; theme: { baseTheme: AgChartThemeName; }; legend: { ...; }; background: { ...; }; }' is not assignable to type 'AgTopologyChartOptions'.
    Types of property 'series' are incompatible.
      Type '{ type: string; xKey: string; yKey: string; }[]' is not assignable to type 'AgTopologySeriesOptions[]'.
        Type '{ type: string; xKey: string; yKey: string; }' is not assignable to type 'AgTopologySeriesOptions'.
          Type '{ type: string; xKey: string; yKey: string; }' is not assignable to type 'AgMapLineBackgroundOptions'.
            Types of property 'type' are incompatible.
              Type 'string' is not assignable to type '"map-line-background"'.

25       <AgChartsReact options={options} />
```

This is simply because one of the option base type is broken. it was typed all lowercase instead of capitalize so it wasn't typescript wasn't processing it as an option in the union check to match the chart option.  

**Expected behavior**
No error should be thrown, if the Cartesian chart base option wasn't broken. but it is. I've got a very simple component 

```
function CustomerGainChart () {
  const [options] = useState<AgCartesianChartOptions>({ 
    title: { text: "Revenue / Profit Week" },
    data: getData(),
    series: [
      { type: 'bar', xKey: 'month', yKey: 'subscriptions'},
      { type: 'line', xKey: 'month', yKey: 'services'}
    ],
    theme:  { baseTheme: 'ag-default-dark' as AgChartThemeName},
    legend: { enabled: false },
    background: {
      fill: "#33333355"
    }
  });
  return  <AgChartsReact options={options} />
}
```

The issue is found in the declaration file ag-charts-cummunity/dist/types/src/options/series/cartesian/cartesianOptions.d.ts  `agbasecartesianchartoptions` was declared instead of `AgBaseCartesianChartOptions`

**Please tell us about your environment:**

MacOS, NeoVim, NPM. 

-   **AG Charts version:** 9.3.1

-   **Browser:** 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

-   **Language:** Typescript 5.2.2 ES2020

**Comment by boldrack** [comment]
Hi, I can send over a fix PR for this if it's allowed. it's a pretty straight forward solution. Just need to rename the declaration with the right casing.

**Comment by AG-DavidG** [comment]
Hi @boldrack 

We have looked into this and have recreated your options in a React TS Plnkr, but do not get the error that you described. 
You can view this at https://plnkr.co/edit/trKjOVOIZbLumIjK?open=index.tsx.

It looks like your install has become corrupted somehow.

If this is not the case, we'd be happy to look into this further, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point.

Thanks 

David

**Comment by boldrack** [comment]
it's Hilarious for me. seem to be a corrupted install. How it happened, i'm not sure. 
i did a fresh install and it was fine. 
Thanks
