### ISSUE TITLE
Rounded series area and line

### ISSUE THREAD

**Issue by ytreu111** [ag-grid/ag-charts#1849]
**I'm submitting a ...** (check one with "x")

```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   A description of the detailed steps to reproduce your behaviour in one of our examples in our docs.
-   A Plunker.

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Now Area and Line series are drawn as straight segments

**Expected behavior**

It would be great to add the ability to round lines
Example
<img width="344" alt="image" src="https://github.com/ag-grid/ag-charts/assets/29800164/e245a950-b2c5-4516-b1f1-5cf4aa62cfff">

- AG Charts version: 9.3.1

-   **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- ALL

**Comment by AG-DavidG** [comment]
Hi @ytreu111 

This functionality will be available in our next release - version 10 - which is due out next month.

You can track it with this reference:
AG-4372 - [Charts] Add support for smooth line series

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Thanks for bringing this up with us.

David
