### ISSUE TITLE
`ag-charts-community` node package contains `/benchmarks` and `__image_snapshots__`

### ISSUE THREAD

**Issue by tagliala** [ag-grid/ag-charts#1939]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Requesting Community Support**

Hi,

I'm not sure that this behaviour is unexpected. I've tried to search for existing issues and inspecting the history of the relevant `.npmignore` but I was not able to find a reference

**Providing a Reproducible Scenario**

-   Download the node package 
-   `du -h node_modules/ag-charts-community/`

**Current behavior**

Includes `/benchmarks` and 4.3MB of `png` files

```
4.3M	node_modules/ag-charts-community/benchmarks/__image_snapshots__
4.3M	node_modules/ag-charts-community/benchmarks
```

**Expected behavior**

Maybe benchmarks should not be included in the production package?

**Please tell us about your environment:**

n/a

-   **AG Charts version:** 9.3.1

-   **Browser:** n/a

-   **Language:** all

**Comment by AG-DavidG** [comment]
Hi @tagliala 

Thank you for reporting this - much appreciated.

We have fixed this in version 10.0.0 which was released today.

Thank you again for getting in touch

David
