### ISSUE TITLE
Problem with animation when data is null

### ISSUE THREAD

**Issue by yousef-langaran** [ag-grid/ag-charts#2284]
Hello, good time
Chart animation crashes when there is null value in my chart data.
When I convert the null values ​​to 0, the animation problem is solved, but I don't want to do this because null means no data came, but 0 means there is data, but it is 0.

**Comment by alantreadway** [comment]
Hi - please submit your bug report following our standard template (hit `New Issue` and populate the presented template), we do not accept reports that are well formed and do not follow that structure.
