### ISSUE TITLE
can't serialize axes label format and formatter anymore?

### ISSUE THREAD

**Issue by kfaiczak** [ag-grid/ag-charts#2717]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

This used to work (and the documentation says you can serialize them

axes: [
        {
            type: 'number',
            position: 'left',
            label: {
                format: '#{->,.2s}',
                formatter: (params) =>
                    params.formatter(params.value).replace('k', 'K')
            },
        },
]

Previous and assumed correct behaviour

if you had a value = 100000
format would make that 100k
then formatter would take the value '100k' and replace that with '100K'

Current behaviour
* format is ignored and formatter is called (the params.value in the formatter is 100000 
thus the same code for value = 100000 
will produce 100000.  (since the replacement was supposed to remove the (s type from format) metric k with a 'K'

MacOS Sonoma 14.5
Chrome Version 128.0.6613.121 
ag-charts 10.0.0 (same with 10.0.2)
React 18.3.1

**Comment by AG-DavidG** [comment]
Hi @kfaiczak 

This has been removed with the reference of AG-11857 in version 10, as we are cleaning up the `format` and `formatter` options. These two should not be used in combination, as they are trying to do similar things in different ways.
 
In this case, you can use the formatter to do all the work without requiring the format option.
 
Javascript has the `compact` format which can be used to directly format the numbers to use 'B' and 'K', without needing to use the format option and then changing it within a formatter.
 
```
      formatter: ({ value }) => {
        return Intl.NumberFormat('en-US', { notation: 'compact' }).format(
          value
        );
      },
```
 
Thanks

David
