### ISSUE TITLE
Feature Request - Support for Maps

### ISSUE THREAD

**Issue by danielmustafa** [ag-grid/ag-charts#849]
**I'm submitting a ...** (check one with "x")

```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hi - My company has an AG Grid license and uses the grid functionality frequently.  Was just going through the ag-charts library and it looks pretty good.  We have several use cases that this would fit, but we have a use case to show a map (ie. US Map) with dots/icons to signify some business metrics at various locations on the map.  Is there any planned support for those types of visuals?  Here's what we use today: https://www.amcharts.com/demos/#maps

**Comment by AG-DavidG** [comment]
Hi @danielmustafa 

Thank you for the question.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

We have added this requirement to our backlog and we are tracking it with the following reference and description:
AG-3319 [Charts] Add Map Visualisation

We have no timeline for this at the moment, but this can still be picked up by our team when they're making modifications to this functional area of AG Charts. Please use the functionality currently provided by AG Charts until this is delivered at a later point.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).

Thanks again for bringing this up with us.

Regards,
